//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.27 at 10:11:58 AM ALMT 
//


package kz.gov.services.gbd.binul;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Основной тип, описывающий классификационные данные юрлица
 * 
 * <p>Java class for AddInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AddInfoType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CreationMethod" type="{http://gbdulinfobybin_v2.egp.gbdul.tamur.kz}DirectoryType"/&gt;
 *         &lt;element name="PropertyType" type="{http://gbdulinfobybin_v2.egp.gbdul.tamur.kz}DirectoryType"/&gt;
 *         &lt;element name="TypicalCharter" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="CommerceOrg" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="EnterpriseSubject" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="FundType" type="{http://gbdulinfobybin_v2.egp.gbdul.tamur.kz}DirectoryType" minOccurs="0"/&gt;
 *         &lt;element name="GosCompanyType" type="{http://gbdulinfobybin_v2.egp.gbdul.tamur.kz}DirectoryType" minOccurs="0"/&gt;
 *         &lt;element name="StatusOO" type="{http://gbdulinfobybin_v2.egp.gbdul.tamur.kz}DirectoryType" minOccurs="0"/&gt;
 *         &lt;element name="Affiliated" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="International" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="ForeignInvest" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="OneCitizenShip" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *         &lt;element name="branchesExistence" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AddInfoType", propOrder = {
    "creationMethod",
    "propertyType",
    "typicalCharter",
    "commerceOrg",
    "enterpriseSubject",
    "fundType",
    "gosCompanyType",
    "statusOO",
    "affiliated",
    "international",
    "foreignInvest",
    "oneCitizenShip",
    "branchesExistence"
})
public class AddInfoType {

    @XmlElement(name = "CreationMethod", required = true)
    protected DirectoryType creationMethod;
    @XmlElement(name = "PropertyType", required = true)
    protected DirectoryType propertyType;
    @XmlElement(name = "TypicalCharter")
    protected boolean typicalCharter;
    @XmlElement(name = "CommerceOrg")
    protected boolean commerceOrg;
    @XmlElement(name = "EnterpriseSubject")
    protected boolean enterpriseSubject;
    @XmlElement(name = "FundType")
    protected DirectoryType fundType;
    @XmlElement(name = "GosCompanyType")
    protected DirectoryType gosCompanyType;
    @XmlElement(name = "StatusOO")
    protected DirectoryType statusOO;
    @XmlElement(name = "Affiliated")
    protected Boolean affiliated;
    @XmlElement(name = "International")
    protected Boolean international;
    @XmlElement(name = "ForeignInvest")
    protected Boolean foreignInvest;
    @XmlElement(name = "OneCitizenShip")
    protected Boolean oneCitizenShip;
    protected Boolean branchesExistence;

    /**
     * Gets the value of the creationMethod property.
     * 
     * @return
     *     possible object is
     *     {@link DirectoryType }
     *     
     */
    public DirectoryType getCreationMethod() {
        return creationMethod;
    }

    /**
     * Sets the value of the creationMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link DirectoryType }
     *     
     */
    public void setCreationMethod(DirectoryType value) {
        this.creationMethod = value;
    }

    /**
     * Gets the value of the propertyType property.
     * 
     * @return
     *     possible object is
     *     {@link DirectoryType }
     *     
     */
    public DirectoryType getPropertyType() {
        return propertyType;
    }

    /**
     * Sets the value of the propertyType property.
     * 
     * @param value
     *     allowed object is
     *     {@link DirectoryType }
     *     
     */
    public void setPropertyType(DirectoryType value) {
        this.propertyType = value;
    }

    /**
     * Gets the value of the typicalCharter property.
     * 
     */
    public boolean isTypicalCharter() {
        return typicalCharter;
    }

    /**
     * Sets the value of the typicalCharter property.
     * 
     */
    public void setTypicalCharter(boolean value) {
        this.typicalCharter = value;
    }

    /**
     * Gets the value of the commerceOrg property.
     * 
     */
    public boolean isCommerceOrg() {
        return commerceOrg;
    }

    /**
     * Sets the value of the commerceOrg property.
     * 
     */
    public void setCommerceOrg(boolean value) {
        this.commerceOrg = value;
    }

    /**
     * Gets the value of the enterpriseSubject property.
     * 
     */
    public boolean isEnterpriseSubject() {
        return enterpriseSubject;
    }

    /**
     * Sets the value of the enterpriseSubject property.
     * 
     */
    public void setEnterpriseSubject(boolean value) {
        this.enterpriseSubject = value;
    }

    /**
     * Gets the value of the fundType property.
     * 
     * @return
     *     possible object is
     *     {@link DirectoryType }
     *     
     */
    public DirectoryType getFundType() {
        return fundType;
    }

    /**
     * Sets the value of the fundType property.
     * 
     * @param value
     *     allowed object is
     *     {@link DirectoryType }
     *     
     */
    public void setFundType(DirectoryType value) {
        this.fundType = value;
    }

    /**
     * Gets the value of the gosCompanyType property.
     * 
     * @return
     *     possible object is
     *     {@link DirectoryType }
     *     
     */
    public DirectoryType getGosCompanyType() {
        return gosCompanyType;
    }

    /**
     * Sets the value of the gosCompanyType property.
     * 
     * @param value
     *     allowed object is
     *     {@link DirectoryType }
     *     
     */
    public void setGosCompanyType(DirectoryType value) {
        this.gosCompanyType = value;
    }

    /**
     * Gets the value of the statusOO property.
     * 
     * @return
     *     possible object is
     *     {@link DirectoryType }
     *     
     */
    public DirectoryType getStatusOO() {
        return statusOO;
    }

    /**
     * Sets the value of the statusOO property.
     * 
     * @param value
     *     allowed object is
     *     {@link DirectoryType }
     *     
     */
    public void setStatusOO(DirectoryType value) {
        this.statusOO = value;
    }

    /**
     * Gets the value of the affiliated property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAffiliated() {
        return affiliated;
    }

    /**
     * Sets the value of the affiliated property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAffiliated(Boolean value) {
        this.affiliated = value;
    }

    /**
     * Gets the value of the international property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isInternational() {
        return international;
    }

    /**
     * Sets the value of the international property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setInternational(Boolean value) {
        this.international = value;
    }

    /**
     * Gets the value of the foreignInvest property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isForeignInvest() {
        return foreignInvest;
    }

    /**
     * Sets the value of the foreignInvest property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setForeignInvest(Boolean value) {
        this.foreignInvest = value;
    }

    /**
     * Gets the value of the oneCitizenShip property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isOneCitizenShip() {
        return oneCitizenShip;
    }

    /**
     * Sets the value of the oneCitizenShip property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setOneCitizenShip(Boolean value) {
        this.oneCitizenShip = value;
    }

    /**
     * Gets the value of the branchesExistence property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isBranchesExistence() {
        return branchesExistence;
    }

    /**
     * Sets the value of the branchesExistence property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBranchesExistence(Boolean value) {
        this.branchesExistence = value;
    }

}
