//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.27 at 10:11:58 AM ALMT 
//


package kz.gov.services.gbd.binul;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Тип описывающий адрес местонахождения  от Комитета Статистики
 * 
 * <p>Java class for AddressStatType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AddressStatType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="RKA" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="KATO" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="NameRu" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="NameKz" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AddressStatType", propOrder = {
    "rka",
    "kato",
    "nameRu",
    "nameKz"
})
public class AddressStatType {

    @XmlElement(name = "RKA")
    protected String rka;
    @XmlElement(name = "KATO")
    protected String kato;
    @XmlElement(name = "NameRu", required = true)
    protected String nameRu;
    @XmlElement(name = "NameKz", required = true)
    protected String nameKz;

    /**
     * Gets the value of the rka property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRKA() {
        return rka;
    }

    /**
     * Sets the value of the rka property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRKA(String value) {
        this.rka = value;
    }

    /**
     * Gets the value of the kato property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getKATO() {
        return kato;
    }

    /**
     * Sets the value of the kato property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setKATO(String value) {
        this.kato = value;
    }

    /**
     * Gets the value of the nameRu property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameRu() {
        return nameRu;
    }

    /**
     * Sets the value of the nameRu property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameRu(String value) {
        this.nameRu = value;
    }

    /**
     * Gets the value of the nameKz property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNameKz() {
        return nameKz;
    }

    /**
     * Sets the value of the nameKz property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNameKz(String value) {
        this.nameKz = value;
    }

}
