//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.27 at 10:11:58 AM ALMT 
//


package kz.gov.services.gbd.binul;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Сведения об уставном капитале
 * 
 * <p>Java class for AuthCapitalType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AuthCapitalType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ValueAll" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="ValueGov" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="PercentGov" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="ValuePrivate" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *         &lt;element name="PercentPrivate" type="{http://www.w3.org/2001/XMLSchema}double"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AuthCapitalType", propOrder = {
    "valueAll",
    "valueGov",
    "percentGov",
    "valuePrivate",
    "percentPrivate"
})
public class AuthCapitalType {

    @XmlElement(name = "ValueAll")
    protected double valueAll;
    @XmlElement(name = "ValueGov")
    protected double valueGov;
    @XmlElement(name = "PercentGov")
    protected double percentGov;
    @XmlElement(name = "ValuePrivate")
    protected double valuePrivate;
    @XmlElement(name = "PercentPrivate")
    protected double percentPrivate;

    /**
     * Gets the value of the valueAll property.
     * 
     */
    public double getValueAll() {
        return valueAll;
    }

    /**
     * Sets the value of the valueAll property.
     * 
     */
    public void setValueAll(double value) {
        this.valueAll = value;
    }

    /**
     * Gets the value of the valueGov property.
     * 
     */
    public double getValueGov() {
        return valueGov;
    }

    /**
     * Sets the value of the valueGov property.
     * 
     */
    public void setValueGov(double value) {
        this.valueGov = value;
    }

    /**
     * Gets the value of the percentGov property.
     * 
     */
    public double getPercentGov() {
        return percentGov;
    }

    /**
     * Sets the value of the percentGov property.
     * 
     */
    public void setPercentGov(double value) {
        this.percentGov = value;
    }

    /**
     * Gets the value of the valuePrivate property.
     * 
     */
    public double getValuePrivate() {
        return valuePrivate;
    }

    /**
     * Sets the value of the valuePrivate property.
     * 
     */
    public void setValuePrivate(double value) {
        this.valuePrivate = value;
    }

    /**
     * Gets the value of the percentPrivate property.
     * 
     */
    public double getPercentPrivate() {
        return percentPrivate;
    }

    /**
     * Sets the value of the percentPrivate property.
     * 
     */
    public void setPercentPrivate(double value) {
        this.percentPrivate = value;
    }

}
