//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.27 at 10:11:58 AM ALMT 
//


package kz.gov.services.gbd.binul;

import javax.xml.datatype.XMLGregorianCalendar;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlSchemaType;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Тип, описывающий данные о ликвидации
 * 
 * <p>Java class for LiquidationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LiquidationType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="LiqBase" type="{http://gbdulinfobybin_v2.egp.gbdul.tamur.kz}DirectoryType" minOccurs="0"/&gt;
 *         &lt;element name="LiqType" type="{http://gbdulinfobybin_v2.egp.gbdul.tamur.kz}DirectoryType" minOccurs="0"/&gt;
 *         &lt;element name="LiqDecisionDate" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/&gt;
 *         &lt;element name="ReorgType" type="{http://gbdulinfobybin_v2.egp.gbdul.tamur.kz}DirectoryType" minOccurs="0"/&gt;
 *         &lt;element name="BinReceiver" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LiquidationType", propOrder = {
    "liqBase",
    "liqType",
    "liqDecisionDate",
    "reorgType",
    "binReceiver"
})
public class LiquidationType {

    @XmlElement(name = "LiqBase")
    protected DirectoryType liqBase;
    @XmlElement(name = "LiqType")
    protected DirectoryType liqType;
    @XmlElement(name = "LiqDecisionDate")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar liqDecisionDate;
    @XmlElement(name = "ReorgType")
    protected DirectoryType reorgType;
    @XmlElement(name = "BinReceiver")
    protected String binReceiver;

    /**
     * Gets the value of the liqBase property.
     * 
     * @return
     *     possible object is
     *     {@link DirectoryType }
     *     
     */
    public DirectoryType getLiqBase() {
        return liqBase;
    }

    /**
     * Sets the value of the liqBase property.
     * 
     * @param value
     *     allowed object is
     *     {@link DirectoryType }
     *     
     */
    public void setLiqBase(DirectoryType value) {
        this.liqBase = value;
    }

    /**
     * Gets the value of the liqType property.
     * 
     * @return
     *     possible object is
     *     {@link DirectoryType }
     *     
     */
    public DirectoryType getLiqType() {
        return liqType;
    }

    /**
     * Sets the value of the liqType property.
     * 
     * @param value
     *     allowed object is
     *     {@link DirectoryType }
     *     
     */
    public void setLiqType(DirectoryType value) {
        this.liqType = value;
    }

    /**
     * Gets the value of the liqDecisionDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getLiqDecisionDate() {
        return liqDecisionDate;
    }

    /**
     * Sets the value of the liqDecisionDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setLiqDecisionDate(XMLGregorianCalendar value) {
        this.liqDecisionDate = value;
    }

    /**
     * Gets the value of the reorgType property.
     * 
     * @return
     *     possible object is
     *     {@link DirectoryType }
     *     
     */
    public DirectoryType getReorgType() {
        return reorgType;
    }

    /**
     * Sets the value of the reorgType property.
     * 
     * @param value
     *     allowed object is
     *     {@link DirectoryType }
     *     
     */
    public void setReorgType(DirectoryType value) {
        this.reorgType = value;
    }

    /**
     * Gets the value of the binReceiver property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBinReceiver() {
        return binReceiver;
    }

    /**
     * Sets the value of the binReceiver property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBinReceiver(String value) {
        this.binReceiver = value;
    }

}
