//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.27 at 10:11:58 AM ALMT 
//


package kz.gov.services.gbd.binul;

import javax.xml.namespace.QName;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the kz.gov.services.gbd.binul package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SendMessageRequest_QNAME = new QName("http://smartbridge.b10.kz", "sendMessageRequest");
    private final static QName _SendMessageResponse_QNAME = new QName("http://smartbridge.b10.kz", "sendMessageResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: kz.gov.services.gbd.binul
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Request }
     * 
     */
    public Request createRequest() {
        return new Request();
    }

    /**
     * Create an instance of {@link Response }
     * 
     */
    public Response createResponse() {
        return new Response();
    }

    /**
     * Create an instance of {@link OrganizationType }
     * 
     */
    public OrganizationType createOrganizationType() {
        return new OrganizationType();
    }

    /**
     * Create an instance of {@link AddInfoType }
     * 
     */
    public AddInfoType createAddInfoType() {
        return new AddInfoType();
    }

    /**
     * Create an instance of {@link PersonType }
     * 
     */
    public PersonType createPersonType() {
        return new PersonType();
    }

    /**
     * Create an instance of {@link LeaderType }
     * 
     */
    public LeaderType createLeaderType() {
        return new LeaderType();
    }

    /**
     * Create an instance of {@link AddressType }
     * 
     */
    public AddressType createAddressType() {
        return new AddressType();
    }

    /**
     * Create an instance of {@link AddressStatType }
     * 
     */
    public AddressStatType createAddressStatType() {
        return new AddressStatType();
    }

    /**
     * Create an instance of {@link ActivityType }
     * 
     */
    public ActivityType createActivityType() {
        return new ActivityType();
    }

    /**
     * Create an instance of {@link LiquidationType }
     * 
     */
    public LiquidationType createLiquidationType() {
        return new LiquidationType();
    }

    /**
     * Create an instance of {@link OrganizationShortType }
     * 
     */
    public OrganizationShortType createOrganizationShortType() {
        return new OrganizationShortType();
    }

    /**
     * Create an instance of {@link HeadType }
     * 
     */
    public HeadType createHeadType() {
        return new HeadType();
    }

    /**
     * Create an instance of {@link DirectoryType }
     * 
     */
    public DirectoryType createDirectoryType() {
        return new DirectoryType();
    }

    /**
     * Create an instance of {@link AuthCapitalType }
     * 
     */
    public AuthCapitalType createAuthCapitalType() {
        return new AuthCapitalType();
    }

    /**
     * Create an instance of {@link StatCommInfoType }
     * 
     */
    public StatCommInfoType createStatCommInfoType() {
        return new StatCommInfoType();
    }

    /**
     * Create an instance of {@link LeaderPositionType }
     * 
     */
    public LeaderPositionType createLeaderPositionType() {
        return new LeaderPositionType();
    }

    /**
     * Create an instance of {@link RemovalType }
     * 
     */
    public RemovalType createRemovalType() {
        return new RemovalType();
    }

    /**
     * Create an instance of {@link IpsNerezType }
     * 
     */
    public IpsNerezType createIpsNerezType() {
        return new IpsNerezType();
    }

    /**
     * Create an instance of {@link LeaderIpsNerezType }
     * 
     */
    public LeaderIpsNerezType createLeaderIpsNerezType() {
        return new LeaderIpsNerezType();
    }

    /**
     * Create an instance of {@link AddressIpsNerezType }
     * 
     */
    public AddressIpsNerezType createAddressIpsNerezType() {
        return new AddressIpsNerezType();
    }

    /**
     * Create an instance of {@link BenefiziarPersonType }
     * 
     */
    public BenefiziarPersonType createBenefiziarPersonType() {
        return new BenefiziarPersonType();
    }

    /**
     * Create an instance of {@link DocumentType }
     * 
     */
    public DocumentType createDocumentType() {
        return new DocumentType();
    }

    /**
     * Create an instance of {@link BenefiziarsType }
     * 
     */
    public BenefiziarsType createBenefiziarsType() {
        return new BenefiziarsType();
    }

    /**
     * Create an instance of {@link ReorganizationType }
     * 
     */
    public ReorganizationType createReorganizationType() {
        return new ReorganizationType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Request }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Request }{@code >}
     */
    @XmlElementDecl(namespace = "http://smartbridge.b10.kz", name = "sendMessageRequest")
    public JAXBElement<Request> createSendMessageRequest(Request value) {
        return new JAXBElement<Request>(_SendMessageRequest_QNAME, Request.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Response }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Response }{@code >}
     */
    @XmlElementDecl(namespace = "http://smartbridge.b10.kz", name = "sendMessageResponse")
    public JAXBElement<Response> createSendMessageResponse(Response value) {
        return new JAXBElement<Response>(_SendMessageResponse_QNAME, Response.class, null, value);
    }

}
