//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.27 at 10:11:58 AM ALMT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://gbdulinfobybin_v2.egp.gbdul.tamur.kz")
package kz.gov.services.gbd.binul;
