//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.27 at 10:11:58 AM ALMT 
//


package kz.gov.services.gbd.binul;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Тип описывающий учредителя - физлицо
 * 
 * <p>Java class for PersonType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PersonType"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Country" type="{http://gbdulinfobybin_v2.egp.gbdul.tamur.kz}DirectoryType" minOccurs="0"/&gt;
 *         &lt;element name="NationalityRelation" type="{http://gbdulinfobybin_v2.egp.gbdul.tamur.kz}DirectoryType" minOccurs="0"/&gt;
 *         &lt;element name="CitizenCountry" type="{http://gbdulinfobybin_v2.egp.gbdul.tamur.kz}DirectoryType" minOccurs="0"/&gt;
 *         &lt;element name="IIN" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="TaxNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="SurName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Name" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="MiddleName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *         &lt;element name="Percent" type="{http://www.w3.org/2001/XMLSchema}double" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PersonType", propOrder = {
    "country",
    "nationalityRelation",
    "citizenCountry",
    "iin",
    "taxNumber",
    "surName",
    "name",
    "middleName",
    "value",
    "percent"
})
public class PersonType {

    @XmlElement(name = "Country")
    protected DirectoryType country;
    @XmlElement(name = "NationalityRelation")
    protected DirectoryType nationalityRelation;
    @XmlElement(name = "CitizenCountry")
    protected DirectoryType citizenCountry;
    @XmlElement(name = "IIN")
    protected String iin;
    @XmlElement(name = "TaxNumber")
    protected String taxNumber;
    @XmlElement(name = "SurName")
    protected String surName;
    @XmlElement(name = "Name")
    protected String name;
    @XmlElement(name = "MiddleName")
    protected String middleName;
    @XmlElement(name = "Value")
    protected Double value;
    @XmlElement(name = "Percent")
    protected Double percent;

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link DirectoryType }
     *     
     */
    public DirectoryType getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link DirectoryType }
     *     
     */
    public void setCountry(DirectoryType value) {
        this.country = value;
    }

    /**
     * Gets the value of the nationalityRelation property.
     * 
     * @return
     *     possible object is
     *     {@link DirectoryType }
     *     
     */
    public DirectoryType getNationalityRelation() {
        return nationalityRelation;
    }

    /**
     * Sets the value of the nationalityRelation property.
     * 
     * @param value
     *     allowed object is
     *     {@link DirectoryType }
     *     
     */
    public void setNationalityRelation(DirectoryType value) {
        this.nationalityRelation = value;
    }

    /**
     * Gets the value of the citizenCountry property.
     * 
     * @return
     *     possible object is
     *     {@link DirectoryType }
     *     
     */
    public DirectoryType getCitizenCountry() {
        return citizenCountry;
    }

    /**
     * Sets the value of the citizenCountry property.
     * 
     * @param value
     *     allowed object is
     *     {@link DirectoryType }
     *     
     */
    public void setCitizenCountry(DirectoryType value) {
        this.citizenCountry = value;
    }

    /**
     * Gets the value of the iin property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIIN() {
        return iin;
    }

    /**
     * Sets the value of the iin property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIIN(String value) {
        this.iin = value;
    }

    /**
     * Gets the value of the taxNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTaxNumber() {
        return taxNumber;
    }

    /**
     * Sets the value of the taxNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTaxNumber(String value) {
        this.taxNumber = value;
    }

    /**
     * Gets the value of the surName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSurName() {
        return surName;
    }

    /**
     * Sets the value of the surName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSurName(String value) {
        this.surName = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the middleName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMiddleName() {
        return middleName;
    }

    /**
     * Sets the value of the middleName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMiddleName(String value) {
        this.middleName = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setValue(Double value) {
        this.value = value;
    }

    /**
     * Gets the value of the percent property.
     * 
     * @return
     *     possible object is
     *     {@link Double }
     *     
     */
    public Double getPercent() {
        return percent;
    }

    /**
     * Sets the value of the percent property.
     * 
     * @param value
     *     allowed object is
     *     {@link Double }
     *     
     */
    public void setPercent(Double value) {
        this.percent = value;
    }

}
