//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.10.27 at 10:11:58 AM ALMT 
//


package kz.gov.services.gbd.binul;

import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * Формат ответа
 * 
 * <p>Java class for Response complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Response"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="Status" type="{http://gbdulinfobybin_v2.egp.gbdul.tamur.kz}DirectoryType"/&gt;
 *         &lt;element name="Organization" type="{http://gbdulinfobybin_v2.egp.gbdul.tamur.kz}OrganizationType" minOccurs="0"/&gt;
 *         &lt;element name="IpsNerezident" type="{http://gbdulinfobybin_v2.egp.gbdul.tamur.kz}IpsNerezType" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Response", propOrder = {
    "status",
    "organization",
    "ipsNerezident"
})
public class Response {

    @XmlElement(name = "Status", required = true)
    protected DirectoryType status;
    @XmlElement(name = "Organization")
    protected OrganizationType organization;
    @XmlElement(name = "IpsNerezident")
    protected IpsNerezType ipsNerezident;

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link DirectoryType }
     *     
     */
    public DirectoryType getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link DirectoryType }
     *     
     */
    public void setStatus(DirectoryType value) {
        this.status = value;
    }

    /**
     * Gets the value of the organization property.
     * 
     * @return
     *     possible object is
     *     {@link OrganizationType }
     *     
     */
    public OrganizationType getOrganization() {
        return organization;
    }

    /**
     * Sets the value of the organization property.
     * 
     * @param value
     *     allowed object is
     *     {@link OrganizationType }
     *     
     */
    public void setOrganization(OrganizationType value) {
        this.organization = value;
    }

    /**
     * Gets the value of the ipsNerezident property.
     * 
     * @return
     *     possible object is
     *     {@link IpsNerezType }
     *     
     */
    public IpsNerezType getIpsNerezident() {
        return ipsNerezident;
    }

    /**
     * Sets the value of the ipsNerezident property.
     * 
     * @param value
     *     allowed object is
     *     {@link IpsNerezType }
     *     
     */
    public void setIpsNerezident(IpsNerezType value) {
        this.ipsNerezident = value;
    }

}
